-- WHO IS THE SENIOR MOST EMOLOYEE BASED ON JOB TITLE 

SELECT * FROM employee
ORDER BY levels DESC 
LIMIT 1 

-- WHICH COUNTRIES HAVE MOST INVOICES 
SELECT COUNT(*) AS c ,billing_country FROM invoice 
GROUP BY billing_country
ORDER BY c DESC

-- WHAT ARE THE 3 TOP VALUES OF TOTAL INVOICE 

SELECT customer_id,total FROM invoice 
ORDER BY total DESC
LIMIT 3

/*	WHICH CITY HAS THE BEST CUSTOMERS? IN WHICH CITY DID WE MAKE THE MOST MONEY?
	WHAT IS THE CITY WITH THE HIGHEST SUM OF INVOICE TOTALS?WHICH CITY SHOULD WE 
	CHOOSE FOR THE PROMOTIONAL MUSIC FESTIVAL BASED ON TOTAL REVENUE? RETURN 
	THE CITY NAME AND THE SUM OF ALL INVOICE TOTALS..*/

SELECT billing_city,SUM(total) AS total FROM invoice 
GROUP BY billing_city
ORDER BY total DESC
LIMIT 1


/*	WHO IS THE BEST CUSTOMER? WHICH CUSTOMER HAS SPENT THE MOST MONEY?RETURN THE 
	CUSTOMER NAME AND THE TOTAL AMOUNT SPENT. IDENTIFY THE CUSTOMER WITH THE HIGHEST 
	SUM OF INVOICE TOTALS.WHO IS THE TOP-SPENDING CUSTOMER?.*/

SELECT c.customer_id,c.first_name,c.last_name,SUM(i.total) AS total 
FROM customer c
JOIN invoice i
ON c.customer_id=i.customer_id
GROUP BY c.customer_id
ORDER BY total DESC
LIMIT 1


